### ISSUE TITLE
Graph gui feature wishlist

### ISSUE THREAD

**Issue by gomoripeti** [Appliscale/xprof#12]
The motivation is that sometimes there are extreme outlier samples which causes the max values being far off from all the other graphs and the other graphs being scaled down to near zero. To have a better idea of the values of the other percentiles I have to suggestions:
- show latest value for each line next to the labels (this way we see eg the value of mean being 0.04 ms although max is 10 ms)
- selectively hide certain graphs eg clicking the label toggles show/hide for the given graph (this way eg max can be hidden and the whole graph can be scaled according to 99 %)

Either or both could be implemented on the js gui.

**Comment by afronski** [comment]
Maybe we could also align grid to left and right axes - currently grid is aligned with left only, maybe there is a way to align it to both.
