### ISSUE TITLE
Removing noise from build files in git status

### ISSUE THREAD

**Issue by MarcinKasprowicz** [Appliscale/xprof#138]
Build files needs to be stored in the repository. Currently each PR in GUI is associated with the necessity of adding or explicitly-no-adding (because of noisy `git status`) `build/` files in to a change. Idea is to separate production build files from development build files.

Production build files should be generated on-demand before each release.
Development build files should be ignored. They should be stored and served from folder `build-dev/`. The folder will be added to .gitignore.

**Comment by gomoripeti** [comment]
Fixed by #140
