### ISSUE TITLE
Update cowboy to newer version (2.X)

### ISSUE THREAD

**Issue by ludwikbukowski** [Appliscale/xprof#164]
Hey

We are struggling to use `xprof` in our projects as cowboy's version is a bit old.

**Comment by ludwikbukowski** [comment]
Ok, I see the master is not updated, but there is a tag version with newer cowboy

**Comment by gomoripeti** [comment]
Hi Ludwik, thanks for the poke: in lack of time I failed to finish proper, final, shiny 2.0.0 (merge to master and tag). I bumped cowboy version on `release_2.0` branch but it is not tagged yet. Until then one can use latest rc version from hex (currently `2.0.0-rc.4`) and override cowboy version to desired one from top level project.
