### ISSUE TITLE
JSON Library Replacement

### ISSUE THREAD

**Issue by afronski** [Appliscale/xprof#20]
Currently using `jiffy` in _Elixir_ projects requires small hack: https://github.com/functional-miners/workshop-production-debugging-ex/blob/master/mix.exs#L44, because new version is not pushed to the *hex.pm* yet.

However we can use different (e.g. purely _Erlang_) lib for that purpose and avoid _NIFs_.

**Comment by ppikula** [comment]
What do you think about this one https://github.com/sile/jsone ?
