### ISSUE TITLE
No error information in UI

### ISSUE THREAD

**Issue by afronski** [Appliscale/xprof#65]
Currently all erroneous situation are silently ignored without any notification in _UI_. We need to provide mechanism for communicating following types of errors:

- [x] Errors in syntax for _XProf query_.
- [x] Errors in impossible situations (e.g. tracing `Elixir.Enum.member?/2` and after similar pattern `Elixir.Enum.member?(_, 2)`.
- [x] Errors for autocompletion (no such pattern found etc.).

**Comment by MarcinKasprowicz** [comment]
We should start with adding for each endpoint non-positive-status-code when something will go wrong. Besides sending status code we should send a message with the reason.
For UI notification we can use toastr library (demo - http://codeseven.github.io/toastr/demo.html)  which is really easy to use From source code it looks following:
```
if some error then
  toastr.error(':(')
```

**Comment by gomoripeti** [comment]
The REST API could have a body like following in case of error
```
{"type": "error"/"warning"/"info"/"success",
  "message": "the error text",
  "column": integer}
```
(column is optional and can be ignored in first iteration. It would mean that there is an error in the query string at the columnth character, so cursor could jump there, blink red, etc)

If the body of a 4xx response is empty, some default error popup should be displayed. (eg "

**Comment by MarcinKasprowicz** [comment]
#137 <- PR

**Comment by gomoripeti** [comment]
With PRs #137 and #142 the bulk of the ticket is addressed (jumping to column is just a futuristic idea that can be addressed later
