### ISSUE TITLE
Tab is crashing after some time

### ISSUE THREAD

**Issue by afronski** [Appliscale/xprof#70]
There is a memory leak on _client side_ that is more visible because of certain _browser_ extensions and it is causing tab to crash after 2-5 minutes. It is related to charts and graphs library.

_Incognito_ mode masks the problem, memory grows - but on smaller rate and you are able to use `xprof` much longer.

**Comment by MarcinKasprowicz** [comment]
I will try to reproduce after changes made in #94

**Comment by MarcinKasprowicz** [comment]
I left xprof open for about 30 minutes. I did not notice any significant raise in memory heap of the application (In my case something like 21MB to 22MB after 30minutes)
