### ISSUE TITLE
Save recent queries

### ISSUE THREAD

**Issue by gomoripeti** [Appliscale/xprof#75]
Keep a list of recent queries in the browser storage (or also in the backend?).

With a keybinding (eg tab, up arrow, down arrow in empty query textbox), button or menu item list recent queries in the drop-down suggestion list and allow searching by prefix (or subtring?) by typing in the query textbox.
Enter on selected list-item should only copy the query to the textbox allowing for further editing (as opposed to normal query input when enter sends the query) (should it? open to discussion)

**Comment by MarcinKasprowicz** [comment]
PR - #139

**Comment by gomoripeti** [comment]
Fixed by #139
