### ISSUE TITLE
Pause time on graph

### ISSUE THREAD

**Issue by gomoripeti** [Appliscale/xprof#76]
Add a button to pause time and temporarily stop updating the graphs. This can be useful if some "extraordinary" event happens and we don't want to let valuable data to slowly slide away.

**Comment by MarcinKasprowicz** [comment]
I will take it

**Comment by afronski** [comment]
@MarcinKasprowicz You can use assignments (you should be able to do it).

**Comment by MarcinKasprowicz** [comment]
PR - https://github.com/Appliscale/xprof/pull/96

**Comment by gomoripeti** [comment]
implemented in #96
