### ISSUE TITLE
FE micro-opt: avoid rendering if not needed

### ISSUE THREAD

**Issue by gomoripeti** [Appliscale/xprof#94]
A `setState` call will always trigger a re-render of the component although maybe nothing has changed. Rendering a component will also trigger re-rendering of its children. Polling functions such as `api/mon_get_all`, `api/trace_status` and `api/capture_data` will usually do not change the state. There are multiple options:
- only call `setState` conditionally if any of the fields in state would change
(eg. like https://github.com/gomoripeti/xprof/commit/8345fd2085e4f01b2b12e80ab9844820f25ff914)
- implement `shouldComponentUpdate()` to check if state changed
- use `React.PureComponent` to automatically detect no change

(https://reactjs.org/docs/react-component.html#setstate)

This optimisation might not give much gain as the most costly to update are the graphs themselves which actually change with every update.

**Comment by MarcinKasprowicz** [comment]
- updateChart function from C3 library is execute ~6times per second. In each second it takes around 300ms.
- https://github.com/maicki/why-did-you-update - library for detecting unnecessary rerenders. It spits out to console those renders. In our case, it goes crazy! We can see that C3 chart component is definitely re-renders too frequently. Our components also rerender too frequently.

The conclusion from me: 
If we want to use React.PureComponent we need to remember that in this case, we will have an only shallow comparison. We mainly use mutable data in props/state.
React documentation encourage to use immutable data together with React.PureComponent. I think it will require no such more work than implementing shouldComponentUpdate() in each component.
Our goals should be to eliminate all unnecessary rerenders pointed by "why-did-you-update".

Moreover I want to give a try with vis.js library for drawing graph (http://visjs.org/examples/graph2d/15_streaming_data.html), I was experimenting with performance and the graph is super smooth. Cons is that it will require more work to set up what we want.

Please tell me what do you think about immutable data + React.PureComponent.

**Comment by Izoslav** [comment]
Imo going with immutable data is worth a shot, it's not that we are changing the values shown in graphs, we only get new ones and render them.

According to [article on react performance](https://benchling.engineering/performance-engineering-with-react-e03013e53285) we shouldn't use function binding as it will always create new function and thus trigger rendering of the component.

**Comment by gomoripeti** [comment]
great investigation guys!
- I would just try first a quick&dirty modification to either implement `shouldComponentUpdate()` for each component of even just put conditions where `setState()` is called, just to see how much these help in performance.
- could the overuse of function bindings be the cause of the memleak? (creating more and more new function objects) this is another lead that could be followed, trying to eliminate them.

I would try these 2 things before looking at a different graph lib.

**Comment by Izoslav** [comment]
Yeah, I think that dynamic creation of functions could lead to memleak, but js gc should be able to handle cleaning of them all. I will investigate it.

**Comment by MarcinKasprowicz** [comment]
CallsTable also needs to be refactored. I put comments in the code - https://github.com/MarcinKasprowicz/xprof/blob/a22ebf1890a34aa3f2cdb76605f6311464d45b62/apps/xprof_gui/priv/app/call_tracer.jsx#L71.
I will continue with that

**Comment by gomoripeti** [comment]
closed by #104 and #106
